commands:
  # 指令
  '/tpa':
    # 当指令有 1 个以上的参数时
    # 才会进行点券判断
    length: 1
    # 需要点券
    points: 100
    # 提示信息
    message: '&4你没有足够的点券这么做'
  # 指令
  '/mp name':
    # 当指令有 3 个以上的参数时
    # 才会进行点券判断
    length: 3
    # 需要点券
    points: 50
    # 提示信息
    message: '&4你没有足够的点券这么做'